import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  Image,
} from "@react-pdf/renderer";

import type { VideoInfo } from "../services/api";
import type { ParsedSummary } from "../utils/parseSummary";

type Props = {
  video: VideoInfo;
  parsed: ParsedSummary;
};
const styles = StyleSheet.create({
  page: {
    padding: 35,
    backgroundColor: "#ffffff",
    fontSize: 11,
    fontFamily: "Helvetica",
  },

  header: {
    borderBottomWidth: 2,
    borderBottomColor: "#2563eb",
    paddingBottom: 12,
    marginBottom: 20,
  },

  logo: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#2563eb",
  },

  subtitle: {
    color: "#666",
    marginTop: 3,
    fontSize: 11,
  },

  thumbnail: {
    width: "100%",
    height: 220,
    objectFit: "cover",
    marginBottom: 20,
  },

  title: {
    fontSize: 22,
    fontWeight: "bold",
    marginBottom: 8,
  },

  channel: {
    color: "#666",
    marginBottom: 20,
  },

  section: {
    marginBottom: 20,
  },

  sectionTitle: {
    fontSize: 18,
    color: "#2563eb",
    marginBottom: 10,
    fontWeight: "bold",
  },

  paragraph: {
    lineHeight: 1.6,
    color: "#333",
  },

  card: {
    borderWidth: 1,
    borderColor: "#dbeafe",
    borderRadius: 8,
    padding: 12,
    marginBottom: 8,
    backgroundColor: "#f8fbff",
  },

  bullet: {
    marginBottom: 6,
  },

  footer: {
    marginTop: 30,
    borderTopWidth: 1,
    borderTopColor: "#ddd",
    paddingTop: 10,
    textAlign: "center",
    color: "#888",
    fontSize: 10,
  },
});
export default function PdfDocument({
  video,
  parsed,
}: Props) {
  return (
    <Document>

      <Page
        size="A4"
        style={styles.page}
      >

        <View style={styles.header}>

          <Text style={styles.logo}>
            BriefTube
          </Text>

          <Text style={styles.subtitle}>
            AI Summary Report
          </Text>

        </View>

        <Image
          src={video.thumbnail}
          style={styles.thumbnail}
        />

        <Text style={styles.title}>
          {video.title}
        </Text>

        <Text style={styles.channel}>
          {video.channel}
        </Text>

        {parsed.executiveSummary ? (
          <View style={styles.section}>

            <Text style={styles.sectionTitle}>
              Executive Summary
            </Text>

            <Text style={styles.paragraph}>
              {parsed.executiveSummary}
            </Text>

          </View>
        ) : null}

        {parsed.keyPoints.length > 0 ? (
          <View style={styles.section}>

            <Text style={styles.sectionTitle}>
              Key Points
            </Text>

            {parsed.keyPoints.map((point, index) => (
              <View
                key={index}
                style={styles.card}
              >
                <Text style={styles.bullet}>
                  {index + 1}. {point}
                </Text>
              </View>
            ))}

          </View>
        ) : null}

        {parsed.keyTakeaways.length > 0 ? (
          <View style={styles.section}>

            <Text style={styles.sectionTitle}>
              Key Takeaways
            </Text>

            {parsed.keyTakeaways.map((item, index) => (
              <View
                key={index}
                style={styles.card}
              >
                <Text>
                  • {item}
                </Text>
              </View>
            ))}

          </View>
        ) : null}

        {parsed.quickSummary ? (
          <View style={styles.section}>

            <Text style={styles.sectionTitle}>
              Quick Summary
            </Text>

            <Text style={styles.paragraph}>
              {parsed.quickSummary}
            </Text>

          </View>
        ) : null}

        {parsed.actionItems.length > 0 ? (
          <View style={styles.section}>

            <Text style={styles.sectionTitle}>
              Action Items
            </Text>

            {parsed.actionItems.map((item, index) => (
              <View
                key={index}
                style={styles.card}
              >
                <Text>
                  ✓ {item}
                </Text>
              </View>
            ))}

          </View>
        ) : null}

        <Text style={styles.footer}>
          Generated by BriefTube AI
        </Text>

      </Page>

    </Document>
  );
}